# Generated by Django 4.1.4 on 2022-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NimapTaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatemodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
