# Generated by Django 4.1.4 on 2022-12-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NimapTaskApp', '0003_alter_topicsmodel_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCreateModel',
            new_name='UserModel',
        ),
    ]
