# Generated by Django 4.1.4 on 2022-12-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NimapTaskApp', '0004_rename_usercreatemodel_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='updated_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topicsmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsmodel',
            name='updated_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
