# Generated by Django 4.1.4 on 2022-12-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NimapTaskApp', '0005_coursemodel_created_date_coursemodel_updated_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='updated_data',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='topicsmodel',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
